version: '3.8'

services:
  arrear-ease:
    build:
      context: .
      args:
        # These need to be set in your deployment environment or a .env file
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    image: arrear-ease:latest
    container_name: arrear-ease
    restart: unless-stopped
    networks:
      - npm_network 

networks:
  npm_network:
    external: true
    # IMPORTANT: This name MUST match the network used by your reverse proxy container.
    # From your screenshot, the correct name is 'npm-network'.
    name: npm-network
