version: '3.8'

services:
  arrear-ease:
    image: ghcr.io/echowkidar/arrear-ease:latest
    container_name: arrear-ease
    restart: unless-stopped
    networks:
      - npm_network
    ports:
      - "3000:3000"

networks:
  npm_network:
    external: true
    name: npm-network
