version: '3.8'

services:
  arrear-ease:
    build:
      context: .
    image: arrear-ease:latest
    container_name: arrear-ease
    restart: unless-stopped
    networks:
      - npm_network
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyDawFh6vd7yU8w0LwyCKlIoP4Cro9O8Bxk"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "arrearease.firebaseapp.com"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: "arrearease"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "arrearease.firebasestorage.app"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "333354527719"
      NEXT_PUBLIC_FIREBASE_APP_ID: "1:333354527719:web:3b58bcc9f93d5d05f46b42"

networks:
  npm_network:
    external: true
    name: npm-network